M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sun Oct  4 09:54:03 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T09:54:03+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X106.0Y-111.11
X106.0Y-116.89
T2
X104.0Y-74.0
X104.0Y-126.0
X176.0Y-74.0
X176.0Y-126.0
M30
